---
title: "Module 5 Report"
author: "ouRduino"
date: "2023-10-10"
output: html_document
bibliogrophy:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Introduction


##Methods


##Results


```{r metadata, echo=FALSE, message=FALSE}
library(tidyverse)
dat.f <- list.files(pattern = "couch|active.csv") #find the files

dat.l <- list() #make an empty list

for(i in dat.f){
  met.dat<- unlist(strsplit(i,"Metadata")) #split of the filename string
  who <- met.data[1] #store the first element
  activity <- gsub(".csv","",met.dat[2]) #store second element, dropping CSV with gsub()
  dat.l[[i]]<- read_csv(i)%>%
    mutate(who=who,activity=activity) #read, then store data with additional columns of metada in list as position unique to i
  
}
dat <- do.call(rbind,dat.l) #combine the list into table

dat%>%
  ggplot()+geom_boxplot(aes(x=activity,y=degC))+facet_grid(.~who) #plot to see what we get
```

##Discussion


##Author Contributions


##References

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
